spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: ${POSTGRES_DRIVER}
    url: ${POSTGRES_URL}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email,profile
            redirect-uri: ${GOOGLE_REDIRECT_URI}
        provider:
          google:
            authorization-uri: ${GOOGLE_AUTHORIZATION_URI}
            token-uri: ${GOOGLE_TOKEN_URI}
            user-info-uri: ${GOOGLE_USER_INFO_URI}
            user-name-attribute: sub
server:
  forward-headers-strategy: framework