spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true